### ISSUE TITLE
Electronic documents for codesets and OpenAPI spec

### ISSUE THREAD

**Issue by Jason-Gush** [new-zealand-research-information-system/nzris-data-specifications#1]
Kia ora MBIE's NZRIS team. 

Great to see this initiative kicking off. 
What would be really useful at the moment would be for the codesets to have their own space, 
and for the OpenAPI spec to be posted and visible.
Looking forward to seeing the content flesh out.

Ngā mihi, Jason.

**Comment by chrisdangerfield** [comment]
Kia ora Jason,

Thanks for your suggestion! Our thoughts as well. We have created [a space for the codesets](https://github.com/new-zealand-research-information-system/nzris-codesets), and a space to hold information related to the [api specifications](https://github.com/new-zealand-research-information-system/nzris-api-specification). Let me know if this aligns with what you were thinking.

Ngā,
Chris

**Comment by Jason-Gush** [comment]
Nice exactly.
