### ISSUE TITLE
Data specifications does not specify whether code or description is needed

### ISSUE THREAD

**Issue by chrisdangerfield** [new-zealand-research-information-system/nzris-data-specifications#2]
The data specifications use codesets, which are a set of allowed values. Currently it is not explicitly stated whether code or description is required, although the [Application Programming Interface specification](https://github.com/new-zealand-research-information-system/nzris-api-specifications) is built to accept codes. 

Submitting codes possibly reduces the chance of error, however it does require source systems to record the code as a code, rather than a description (eg systems would need to record "O" for "Open data" in the "Access Type" codeset).

**Comment by Jason-Gush** [comment]
Thanks Chris, 
This is how we were treating it, but nice to have the confirmation.
For those who'll be using the Excel route, is the intention to be forgiving or whether code or description is provided?

**Comment by chrisdangerfield** [comment]
Kia ora Jason,

Great that it sounds like it will work for you. I understand our database developers are going to build to accept values from either - but not a mix. This will enable users of the Excel template to enter in description values rather than having to translate to codes.

We will possibly need to add a note to the data spec, so that it is explicit.

Ngā,
Chris

**Comment by melissafordyce** [comment]
We can now confirm that either code or description can be provided via either the API or the submission Excel template. 

The Custodian Application will validate both types, and will provide a view of the data that is provided without transformation (so if a code is provided, the Custodian Application will not transform it to the description). 

The NZRIS public website will show both code and description for code set values, regardless of what is provided.

**Comment by melissafordyce** [comment]
Clarification about this has been added to v2.01 of the NZRIS Data Spec, August 2020, page 15.
