### ISSUE TITLE
Description of ANZSRC codes differs

### ISSUE THREAD

**Issue by LizzieTrickett** [new-zealand-research-information-system/nzris-data-specifications#21]
In Award Granted the description for the ANZSRC sub-entity's is 'the distribution of resources by ANZSRC...' (Page 47 of v2.0 of the data specification)

In the sub-entity the description is the proportion of focus within the project. (page 52, 53 and 54).

This occurs in the Application, and Project entities as well. 
![image](https://user-images.githubusercontent.com/58486769/70082471-5b781a00-166f-11ea-9bac-fcc48554562a.png)
![image](https://user-images.githubusercontent.com/58486769/70082514-6df25380-166f-11ea-8fe4-ea11b0e01b9f.png)

**Comment by melissafordyce** [comment]
Updated in NZRIS Data Specification v2.01, August 2020.
