### ISSUE TITLE
Change in the function of the “person identifiable” protection pattern on the person entity 

### ISSUE THREAD

**Issue by chrisdangerfield** [new-zealand-research-information-system/nzris-data-specifications#24]
The person identifiable protection pattern functionality has been changed in the NZRIS system to allow the display of “Given Name” and “Family Name” even when the person identifiable protection pattern is used. This is to allow the display of researchers’ names already publically released.

If a record links to a person record that has personal identifiable pattern on it, the linked ID will be shown as a link AND masked.

**Comment by melissafordyce** [comment]
Updated in NZRIS Data Spec v2.01 August 2020.
