### ISSUE TITLE
Mandatory information noted in summary table is confusing

### ISSUE THREAD

**Issue by chrisdangerfield** [new-zealand-research-information-system/nzris-data-specifications#3]
There are some data fields listed as non-mandatory in the summary table but are "conditionally mandatory" in "guidance" text. For example "Resource Measure – Currency" is listed under the "optional or conditional" column for "Resource Distributed" but is mandatory if particular "Resource Type" values are used.

**Comment by melissafordyce** [comment]
This guidance has been updated in v2.01 of the NZRIS Data Specifications August 2020, both in the summary tables and in the data guidance for each data field so that it is clear when a field must be provided based on another field.
